// ─── DHF Markdown Exporter ───────────────────────────────────────────────────
//
// Renders Document IR to GitHub-Flavored Markdown (GFM).
// ─────────────────────────────────────────────────────────────────────────────

import type { DhfExportPlugin, DhfExportResult } from '../export-plugin.js';
import type {
    DhfDocument, DhfBlock, DhfInline,
    DhfText, DhfXref, DhfTable, DhfList, DhfParagraph,
    DhfHeading, DhfBadge, DhfMetric, DhfMetricGroup, DhfProgress,
} from '../document-ir.js';

export class MarkdownExportPlugin implements DhfExportPlugin {
    format = 'md' as const;
    extension = '.md';
    mimeType = 'text/markdown';

    async render(doc: DhfDocument): Promise<DhfExportResult> {
        const md = renderDocument(doc);
        return { format: 'md', content: md, extension: '.md', mimeType: 'text/markdown' };
    }
}

function renderDocument(doc: DhfDocument): string {
    const { frontmatter, sections } = doc;
    const lines: string[] = [];

    // YAML frontmatter
    lines.push('---');
    lines.push(`title: "${frontmatter.title}"`);
    lines.push(`document_id: ${frontmatter.documentId}`);
    if (frontmatter.project) lines.push(`project: "${frontmatter.project}"`);
    if (frontmatter.organization) lines.push(`organization: "${frontmatter.organization}"`);
    if (frontmatter.version) lines.push(`version: "${frontmatter.version}"`);
    if (frontmatter.phase) lines.push(`phase: "${frontmatter.phase}"`);
    lines.push(`generated_at: "${frontmatter.generatedAt}"`);
    if (frontmatter.standards && frontmatter.standards.length > 0) {
        lines.push(`standards:`);
        for (const s of frontmatter.standards) lines.push(`  - "${s}"`);
    }
    lines.push('---');
    lines.push('');

    // Title
    lines.push(`# ${frontmatter.title}`);
    lines.push('');
    const meta: string[] = [];
    if (frontmatter.project) meta.push(frontmatter.project);
    if (frontmatter.organization) meta.push(frontmatter.organization);
    meta.push(`Generated ${new Date(frontmatter.generatedAt).toLocaleDateString()}`);
    lines.push(`*${meta.join(' | ')}*`);
    lines.push('');

    // TOC
    lines.push('## Table of Contents');
    lines.push('');
    for (let i = 0; i < sections.length; i++) {
        const s = sections[i];
        const anchor = s.id.replace(/[^a-z0-9-]/g, '-');
        const statusTag = s.status ? ` \`${s.status}\`` : '';
        lines.push(`${i + 1}. [${s.title}](#${anchor})${statusTag}`);
    }
    lines.push('');

    // Sections
    for (const section of sections) {
        lines.push(`## ${section.title}`);
        lines.push('');
        for (const block of section.blocks) {
            lines.push(renderBlock(block));
            lines.push('');
        }
    }

    // Approvers
    if (frontmatter.approvers && frontmatter.approvers.length > 0) {
        lines.push('## Approvals');
        lines.push('');
        lines.push('| Name | Role | Date | Signature |');
        lines.push('|------|------|------|-----------|');
        for (const a of frontmatter.approvers) {
            lines.push(`| ${a.name} | ${a.role} | ${a.date || '________'} | ________ |`);
        }
        lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by MEMO Architect — ${frontmatter.generatedAt}*`);

    return lines.join('\n');
}

function renderBlock(block: DhfBlock): string {
    switch (block.type) {
        case 'heading': {
            const prefix = '#'.repeat(block.level + 1); // offset by 1 since section is h2
            return `${prefix} ${block.text}`;
        }
        case 'paragraph': return renderParagraph(block);
        case 'table': return renderTable(block);
        case 'list': return renderList(block);
        case 'badge': return `**\`${block.label}\`**`;
        case 'metric': return `- **${block.label}:** ${block.value}${block.unit ? ` ${block.unit}` : ''}`;
        case 'metric-group': return block.metrics.map(m =>
            `| **${m.label}** | ${m.value}${m.unit ? ` ${m.unit}` : ''} |`
        ).join('\n');
        case 'progress': {
            const pct = block.max > 0 ? Math.round(block.value / block.max * 100) : 0;
            return `**${block.label}:** ${block.value}/${block.max} (${pct}%)`;
        }
        case 'divider': return '---';
        default: return '';
    }
}

function renderParagraph(p: DhfParagraph): string {
    return p.content.map(renderInline).join('');
}

function renderInline(inline: DhfInline): string {
    if (inline.type === 'text') return renderText(inline);
    if (inline.type === 'xref') return `**${inline.label}**`;
    if (inline.type === 'badge') return `**\`${inline.label}\`**`;
    return '';
}

function renderText(t: DhfText): string {
    let s = t.value;
    if (t.code) s = `\`${s}\``;
    if (t.bold) s = `**${s}**`;
    if (t.italic) s = `*${s}*`;
    if (t.change === 'added') s = `++${s}++`;
    if (t.change === 'removed') s = `~~${s}~~`;
    return s;
}

function renderTable(t: DhfTable): string {
    const lines: string[] = [];
    const headers = t.headers.map(h => h.content.map(renderInline).join(''));
    lines.push(`| ${headers.join(' | ')} |`);
    lines.push(`| ${headers.map(() => '---').join(' | ')} |`);
    for (const row of t.rows) {
        const cells = row.cells.map(c => c.content.map(renderInline).join(''));
        lines.push(`| ${cells.join(' | ')} |`);
    }
    if (t.caption) lines.push(`*${t.caption}*`);
    return lines.join('\n');
}

function renderList(l: DhfList): string {
    return l.items.map((item, i) => {
        const prefix = l.ordered ? `${i + 1}.` : '-';
        return `${prefix} ${item.map(renderInline).join('')}`;
    }).join('\n');
}
