// ─── DHF HTML Exporter ───────────────────────────────────────────────────────
//
// Renders Document IR to standalone HTML with embedded CSS.
// Supports redline markup for change tracking.
// ─────────────────────────────────────────────────────────────────────────────

import type { DhfExportPlugin, DhfExportResult } from '../export-plugin.js';
import type {
    DhfDocument, DhfDocumentSection, DhfBlock, DhfInline,
    DhfText, DhfXref, DhfTable, DhfList, DhfParagraph,
    DhfHeading, DhfBadge, DhfMetric, DhfMetricGroup, DhfProgress, DhfDivider,
} from '../document-ir.js';

function esc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export class HtmlExportPlugin implements DhfExportPlugin {
    format = 'html' as const;
    extension = '.html';
    mimeType = 'text/html';

    async render(doc: DhfDocument): Promise<DhfExportResult> {
        const html = renderDocument(doc);
        return { format: 'html', content: html, extension: '.html', mimeType: 'text/html' };
    }
}

function renderDocument(doc: DhfDocument): string {
    const { frontmatter, sections } = doc;
    const date = new Date(frontmatter.generatedAt).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
    });

    let html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(frontmatter.title)} — ${esc(frontmatter.project || '')}</title>
${CSS}
</head>
<body>
<div class="container">
  <header class="doc-header">
    <h1>${esc(frontmatter.title)}</h1>
    <div class="meta">
      <span>${esc(frontmatter.project || '')}</span>
      ${frontmatter.organization ? `<span>&middot; ${esc(frontmatter.organization)}</span>` : ''}
      <span>&middot; ${date}</span>
      ${frontmatter.version ? `<span>&middot; v${esc(frontmatter.version)}</span>` : ''}
    </div>
    ${frontmatter.standards && frontmatter.standards.length > 0 ? `
    <div class="standards">Standards: ${frontmatter.standards.map(s => esc(s)).join(', ')}</div>` : ''}
  </header>

  <nav class="toc">
    <h2>Table of Contents</h2>
    <ol>
      ${sections.map(s => `<li><a href="#${esc(s.id)}">${esc(s.title)}</a> ${renderStatusBadgeInline(s.status)}</li>`).join('\n      ')}
    </ol>
  </nav>
`;

    for (const section of sections) {
        html += `
  <section id="${esc(section.id)}" class="doc-section">
    <h2>${esc(section.title)} ${renderStatusBadgeInline(section.status)}</h2>
    ${section.blocks.map(renderBlock).join('\n    ')}
  </section>`;
    }

    // Footer with approvers
    html += `
  <footer class="doc-footer">`;

    if (frontmatter.approvers && frontmatter.approvers.length > 0) {
        html += `
    <h3>Approvals</h3>
    <table>
      <thead><tr><th>Name</th><th>Role</th><th>Date</th><th>Signature</th></tr></thead>
      <tbody>
        ${frontmatter.approvers.map(a => `<tr><td>${esc(a.name)}</td><td>${esc(a.role)}</td><td>${esc(a.date || '________')}</td><td>________________</td></tr>`).join('\n        ')}
      </tbody>
    </table>`;
    }

    html += `
    <div class="gen-info">Generated by MEMO Architect &middot; ${esc(frontmatter.generatedAt)}</div>
  </footer>
</div>
</body>
</html>`;

    return html;
}

function renderStatusBadgeInline(status?: string): string {
    if (!status) return '';
    const cls = status === 'complete' ? 'badge-ok' : status === 'partial' ? 'badge-warning' : 'badge-error';
    return `<span class="badge ${cls}">${esc(status)}</span>`;
}

function renderBlock(block: DhfBlock): string {
    switch (block.type) {
        case 'heading': return renderHeading(block);
        case 'paragraph': return renderParagraph(block);
        case 'table': return renderTable(block);
        case 'list': return renderList(block);
        case 'badge': return renderBadge(block);
        case 'metric': return renderMetric(block);
        case 'metric-group': return renderMetricGroup(block);
        case 'progress': return renderProgress(block);
        case 'divider': return '<hr class="divider">';
        default: return '';
    }
}

function renderHeading(h: DhfHeading): string {
    const tag = `h${h.level}`;
    return `<${tag}${h.id ? ` id="${esc(h.id)}"` : ''}>${esc(h.text)}</${tag}>`;
}

function renderParagraph(p: DhfParagraph): string {
    const changeCls = p.change ? ` class="change-${p.change}"` : '';
    return `<p${changeCls}>${p.content.map(renderInline).join('')}</p>`;
}

function renderInline(inline: DhfInline): string {
    if (inline.type === 'text') return renderText(inline);
    if (inline.type === 'xref') return renderXref(inline);
    if (inline.type === 'badge') return `<span class="badge badge-${inline.variant}">${esc(inline.label)}</span>`;
    return '';
}

function renderText(t: DhfText): string {
    let s = esc(t.value);
    if (t.code) s = `<code>${s}</code>`;
    if (t.bold) s = `<strong>${s}</strong>`;
    if (t.italic) s = `<em>${s}</em>`;
    if (t.change === 'added') s = `<ins class="redline-add">${s}</ins>`;
    if (t.change === 'removed') s = `<del class="redline-del">${s}</del>`;
    return s;
}

function renderXref(x: DhfXref): string {
    return `<span class="xref" data-element-id="${esc(x.elementId)}" title="${esc(x.kind || '')}">${esc(x.label)}</span>`;
}

function renderTable(t: DhfTable): string {
    let html = '<table>';
    if (t.caption) html += `<caption>${esc(t.caption)}</caption>`;
    html += '<thead><tr>';
    for (const h of t.headers) {
        html += `<th>${h.content.map(renderInline).join('')}</th>`;
    }
    html += '</tr></thead><tbody>';
    for (const row of t.rows) {
        const changeCls = row.change ? ` class="change-${row.change}"` : '';
        html += `<tr${changeCls}>`;
        for (const cell of row.cells) {
            const tag = cell.header ? 'th' : 'td';
            const span = (cell.colSpan ? ` colspan="${cell.colSpan}"` : '')
                + (cell.rowSpan ? ` rowspan="${cell.rowSpan}"` : '');
            html += `<${tag}${span}>${cell.content.map(renderInline).join('')}</${tag}>`;
        }
        html += '</tr>';
    }
    html += '</tbody></table>';
    return html;
}

function renderList(l: DhfList): string {
    const tag = l.ordered ? 'ol' : 'ul';
    const items = l.items.map(item => `<li>${item.map(renderInline).join('')}</li>`).join('\n');
    return `<${tag}>${items}</${tag}>`;
}

function renderBadge(b: DhfBadge): string {
    return `<span class="badge badge-${b.variant}">${esc(b.label)}</span>`;
}

function renderMetric(m: DhfMetric): string {
    const variantCls = m.variant ? ` metric-${m.variant}` : '';
    return `<div class="metric${variantCls}">
    <div class="metric-value">${esc(String(m.value))}${m.unit ? `<span class="metric-unit">${esc(m.unit)}</span>` : ''}</div>
    <div class="metric-label">${esc(m.label)}</div>
  </div>`;
}

function renderMetricGroup(mg: DhfMetricGroup): string {
    return `<div class="metric-group">${mg.metrics.map(renderMetric).join('\n')}</div>`;
}

function renderProgress(p: DhfProgress): string {
    const rawPct = p.max > 0 ? Math.round(p.value / p.max * 100) : 0;
    const pct = Math.max(0, Math.min(100, rawPct));
    const color = p.color || (pct >= 80 ? '#10b981' : pct >= 50 ? '#d97706' : '#dc2626');
    return `<div class="progress-bar">
    <div class="progress-label">${esc(p.label)}: ${p.value}/${p.max} (${pct}%)</div>
    <div class="progress-track"><div class="progress-fill" style="width:${pct}%;background:${esc(color)}"></div></div>
  </div>`;
}

const CSS = `<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; background: #fff; line-height: 1.6; font-size: 14px; }
  .container { max-width: 900px; margin: 0 auto; padding: 40px 32px; }
  .doc-header { margin-bottom: 32px; border-bottom: 3px solid #2DD4A8; padding-bottom: 16px; }
  .doc-header h1 { font-size: 24px; font-weight: 700; color: #1B3A4B; }
  .meta { color: #6B7280; font-size: 13px; margin-top: 4px; }
  .meta span + span { margin-left: 4px; }
  .standards { color: #6B7280; font-size: 12px; margin-top: 8px; font-style: italic; }
  .toc { background: #f8f9fa; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px 24px; margin-bottom: 32px; }
  .toc h2 { font-size: 14px; font-weight: 600; color: #374151; margin-bottom: 8px; }
  .toc ol { padding-left: 20px; font-size: 13px; }
  .toc li { margin: 4px 0; }
  .toc a { color: #2563eb; text-decoration: none; }
  .toc a:hover { text-decoration: underline; }
  .doc-section { margin-bottom: 32px; }
  .doc-section h2 { font-size: 18px; font-weight: 600; color: #1B3A4B; margin-bottom: 12px; padding-bottom: 6px; border-bottom: 2px solid #2DD4A8; }
  h3 { font-size: 15px; font-weight: 600; color: #374151; margin: 16px 0 8px; }
  h4 { font-size: 14px; font-weight: 600; color: #374151; margin: 12px 0 6px; }
  p { margin: 8px 0; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }
  th, td { padding: 8px 12px; border: 1px solid #e5e7eb; text-align: left; }
  th { background: #f3f4f6; font-weight: 600; color: #374151; }
  tr:nth-child(even) { background: #f9fafb; }
  caption { font-size: 12px; color: #6B7280; margin-bottom: 4px; text-align: left; font-style: italic; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge-success, .badge-ok { background: #ecfdf5; color: #059669; }
  .badge-warning { background: #fffbeb; color: #d97706; }
  .badge-error { background: #fef2f2; color: #dc2626; }
  .badge-info { background: #eff6ff; color: #2563eb; }
  .badge-neutral { background: #f3f4f6; color: #6B7280; }
  .badge-partial { background: #fffbeb; color: #d97706; }
  .badge-empty { background: #fef2f2; color: #dc2626; }
  .badge-complete { background: #ecfdf5; color: #059669; }
  .xref { color: #2563eb; font-weight: 500; cursor: help; border-bottom: 1px dotted #2563eb; }
  .metric-group { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin: 12px 0; }
  .metric { background: #f8f9fa; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px; text-align: center; }
  .metric-value { font-size: 24px; font-weight: 700; color: #1B3A4B; }
  .metric-unit { font-size: 12px; color: #6B7280; margin-left: 2px; }
  .metric-label { font-size: 11px; color: #6B7280; margin-top: 2px; }
  .metric-success .metric-value { color: #059669; }
  .metric-warning .metric-value { color: #d97706; }
  .metric-error .metric-value { color: #dc2626; }
  .progress-bar { margin: 8px 0; }
  .progress-label { font-size: 12px; color: #374151; margin-bottom: 4px; }
  .progress-track { background: #e5e7eb; border-radius: 4px; height: 8px; overflow: hidden; }
  .progress-fill { height: 100%; border-radius: 4px; transition: width 0.3s; }
  .divider { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
  .redline-add { background: #dcfce7; color: #166534; text-decoration: none; }
  .redline-del { background: #fef2f2; color: #991b1b; text-decoration: line-through; }
  .change-added { background: #f0fdf4; }
  .change-removed { background: #fef2f2; text-decoration: line-through; }
  .doc-footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #e5e7eb; }
  .doc-footer h3 { font-size: 14px; margin-bottom: 12px; }
  .gen-info { color: #9ca3af; font-size: 11px; margin-top: 16px; }
  ul, ol { padding-left: 20px; margin: 8px 0; }
  li { margin: 4px 0; }
  code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-size: 12px; }
  @media print {
    .container { max-width: 100%; padding: 20px; }
    .toc { break-after: page; }
    .doc-section { break-inside: avoid-page; }
  }
</style>`;
