import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import chalk from 'chalk';
import type { ArchetypeInfo } from './archetype-loader.js';

type RegulatoryClass = 'class-i' | 'class-ii' | 'class-iii-iib';

interface RegulatoryInfo {
    id: RegulatoryClass;
    label: string;
    standards: string;
}

const REGULATORY_CLASSES: RegulatoryInfo[] = [
    { id: 'class-i',       label: 'Class I / Low Risk',              standards: 'ISO 14971 (risk), IEC 62366 (usability)' },
    { id: 'class-ii',      label: 'Class II / Moderate Risk',        standards: '+ IEC 62304 (software lifecycle), 21 CFR 820' },
    { id: 'class-iii-iib', label: 'Class III / High Risk (EU IIb+)', standards: '+ full DHF, clinical evaluation, PMA/EU MDR' },
];

export interface WizardResult {
    archetypeId: string;
    regulatoryClass: RegulatoryClass;
}

export async function runWizard(archetypes: ArchetypeInfo[]): Promise<WizardResult> {
    const rl = createInterface({ input, output });
    const choices = archetypes.filter(a => a.id !== 'blank');

    console.log(chalk.bold('\n🧙 MEMO Startup Wizard\n'));
    console.log(chalk.gray('  Answer a few questions and we\'ll scaffold the right starter model.\n'));

    console.log(chalk.bold('  What type of medical device are you building?\n'));
    choices.forEach((a, i) => {
        console.log(`  ${chalk.cyan(`${i + 1}.`)} ${chalk.white(a.label)}`);
        console.log(`     ${chalk.gray(a.description)}`);
    });

    let archetypeIndex = -1;
    while (archetypeIndex < 0 || archetypeIndex >= choices.length) {
        const raw = await rl.question(chalk.gray(`\n  Select [1-${choices.length}]: `));
        const parsed = parseInt(raw.trim(), 10);
        if (!isNaN(parsed) && parsed >= 1 && parsed <= choices.length) {
            archetypeIndex = parsed - 1;
        } else {
            console.log(chalk.yellow(`  Please enter a number between 1 and ${choices.length}.`));
        }
    }
    const archetype = choices[archetypeIndex];
    console.log(chalk.green(`  ✓ ${archetype.label}\n`));

    console.log(chalk.bold('  What is your expected regulatory classification?\n'));
    REGULATORY_CLASSES.forEach((rc, i) => {
        console.log(`  ${chalk.cyan(`${i + 1}.`)} ${chalk.white(rc.label)}`);
        console.log(`     ${chalk.gray(rc.standards)}`);
    });

    let regIndex = -1;
    while (regIndex < 0 || regIndex >= REGULATORY_CLASSES.length) {
        const raw = await rl.question(chalk.gray(`\n  Select [1-${REGULATORY_CLASSES.length}]: `));
        const parsed = parseInt(raw.trim(), 10);
        if (!isNaN(parsed) && parsed >= 1 && parsed <= REGULATORY_CLASSES.length) {
            regIndex = parsed - 1;
        } else {
            console.log(chalk.yellow(`  Please enter a number between 1 and ${REGULATORY_CLASSES.length}.`));
        }
    }
    const regulatoryClass = REGULATORY_CLASSES[regIndex];
    console.log(chalk.green(`  ✓ ${regulatoryClass.label}\n`));

    rl.close();

    return {
        archetypeId: archetype.id,
        regulatoryClass: regulatoryClass.id,
    };
}

export function regulatoryComment(regulatoryClass: RegulatoryClass, archetypeLabel: string): string {
    const standards: Record<RegulatoryClass, string[]> = {
        'class-i': ['ISO 14971 (risk management)', 'IEC 62366 (usability engineering)'],
        'class-ii': ['ISO 14971', 'IEC 62366', 'IEC 62304 (software lifecycle)', '21 CFR 820 / ISO 13485'],
        'class-iii-iib': ['ISO 14971', 'IEC 62366', 'IEC 62304', '21 CFR 820 / ISO 13485', 'Clinical evaluation (EU MDR Annex XIV)'],
    };
    const lines = standards[regulatoryClass].map(s => `// • ${s}`).join('\n');
    return `// Regulatory classification: ${REGULATORY_CLASSES.find(r => r.id === regulatoryClass)?.label}
// Applicable standards for this project:
${lines}
//
// Generated by memo init — update intended use statement before sharing.`;
}
