#:schema https://docs.sensmetry.com/schemas/latest/syside.schema.json

include = [
    "model",
    "node_modules/@memoarchitect/ontology/src",
]

exclude = [
    ".memo",
    ".sysand",
    "dist",
    "output",
]
